"""
Word list for the 'words' corpus, organised by semantic category.

Each entry is embedded as "word (category)" for unambiguous retrieval.
Add / remove words here and re-run words_pipeline.py to regenerate the corpus.
"""

# Dict[category_label, list[word]]
WORD_CATEGORIES: dict[str, list[str]] = {
    "mammal": [
        "dog", "cat", "horse", "cow", "pig", "sheep", "goat", "rabbit", "hamster", "guinea pig",
        "wolf", "fox", "coyote", "jackal", "hyena", "lion", "tiger", "leopard", "cheetah", "jaguar",
        "puma", "lynx", "bobcat", "bear", "polar bear", "grizzly", "panda", "koala", "kangaroo",
        "wallaby", "wombat", "platypus", "hedgehog", "porcupine", "badger", "otter", "beaver",
        "raccoon", "skunk", "meerkat", "mongoose", "ferret", "mink", "weasel", "stoat",
        "elephant", "rhinoceros", "hippopotamus", "giraffe", "zebra", "wildebeest", "bison",
        "buffalo", "yak", "moose", "deer", "elk", "reindeer", "caribou", "antelope", "gazelle",
        "gorilla", "chimpanzee", "bonobo", "orangutan", "gibbon", "baboon", "macaque", "lemur",
        "whale", "dolphin", "porpoise", "orca", "narwhal", "manatee", "dugong", "seal",
        "sea lion", "walrus", "bat", "mole", "shrew", "vole", "rat", "mouse", "squirrel",
        "chipmunk", "prairie dog", "capybara", "armadillo", "anteater", "sloth",
    ],
    "bird": [
        "eagle", "hawk", "falcon", "osprey", "kite", "harrier", "vulture", "condor",
        "owl", "barn owl", "penguin", "albatross", "pelican", "flamingo", "heron", "crane",
        "stork", "ibis", "spoonbill", "swan", "goose", "duck", "mallard", "teal",
        "parrot", "macaw", "cockatoo", "parakeet", "toucan", "hornbill", "kingfisher",
        "hummingbird", "swift", "swallow", "martin", "robin", "sparrow", "finch", "wren",
        "thrush", "blackbird", "starling", "crow", "raven", "magpie", "jay", "jackdaw",
        "pigeon", "dove", "cuckoo", "woodpecker", "nuthatch", "tit", "warbler", "nightingale",
        "lark", "skylark", "partridge", "pheasant", "peacock", "ostrich", "emu", "cassowary",
        "kiwi", "roadrunner", "puffin", "gannet", "cormorant", "booby", "frigate bird",
    ],
    "reptile and amphibian": [
        "snake", "cobra", "python", "boa constrictor", "rattlesnake", "mamba", "viper",
        "anaconda", "king snake", "garter snake", "lizard", "gecko", "iguana", "chameleon",
        "komodo dragon", "monitor lizard", "skink", "salamander", "crocodile", "alligator",
        "gharial", "caiman", "turtle", "tortoise", "sea turtle", "terrapin",
        "frog", "tree frog", "bullfrog", "toad", "newt", "axolotl",
    ],
    "fish and sea creature": [
        "salmon", "tuna", "cod", "herring", "mackerel", "sardine", "anchovy", "trout",
        "bass", "perch", "pike", "carp", "catfish", "tilapia", "halibut", "flounder",
        "sole", "swordfish", "marlin", "sailfish", "barracuda", "grouper", "snapper",
        "shark", "hammerhead", "great white", "whale shark", "ray", "manta ray", "stingray",
        "eel", "moray eel", "seahorse", "pipefish", "clownfish", "angelfish", "pufferfish",
        "octopus", "squid", "cuttlefish", "nautilus", "jellyfish", "starfish", "sea urchin",
        "sea cucumber", "coral", "anemone", "crab", "lobster", "shrimp", "prawn", "krill",
        "barnacle", "mussel", "oyster", "clam", "scallop", "snail", "slug",
    ],
    "insect and arthropod": [
        "ant", "bee", "bumblebee", "wasp", "hornet", "termite", "cricket", "grasshopper",
        "locust", "cockroach", "mantis", "stick insect", "butterfly", "moth", "caterpillar",
        "dragonfly", "damselfly", "firefly", "beetle", "ladybug", "weevil", "scarab",
        "mosquito", "fly", "horsefly", "flea", "louse", "bedbug", "mite", "tick",
        "spider", "tarantula", "black widow", "scorpion", "centipede", "millipede",
        "woodlouse", "earwig", "silverfish", "mayfly",
    ],
    "food dish": [
        "pizza", "pasta", "spaghetti", "lasagna", "risotto", "gnocchi", "ravioli",
        "burger", "sandwich", "hot dog", "taco", "burrito", "quesadilla", "enchilada",
        "sushi", "sashimi", "ramen", "udon", "tempura", "teriyaki", "miso",
        "curry", "biryani", "tikka masala", "samosa", "naan", "chapati",
        "steak", "roast", "stew", "casserole", "soup", "broth", "chowder",
        "salad", "coleslaw", "hummus", "falafel", "kebab", "shawarma",
        "omelette", "quiche", "crepe", "waffle", "pancake", "french toast",
        "pie", "cake", "tart", "muffin", "croissant", "bagel", "pretzel",
        "ice cream", "sorbet", "pudding", "custard", "brownie", "cookie",
        "fried rice", "paella", "gumbo", "jambalaya", "couscous", "tagine",
        "dumplings", "spring roll", "dim sum", "pho", "pad thai", "satay",
    ],
    "fruit": [
        "apple", "pear", "peach", "plum", "apricot", "cherry", "grape", "fig",
        "banana", "mango", "papaya", "pineapple", "guava", "lychee", "rambutan",
        "durian", "jackfruit", "passion fruit", "dragon fruit", "starfruit",
        "orange", "lemon", "lime", "grapefruit", "tangerine", "clementine",
        "strawberry", "raspberry", "blueberry", "blackberry", "cranberry", "gooseberry",
        "watermelon", "cantaloupe", "honeydew", "kiwi", "pomegranate", "persimmon",
        "quince", "mulberry", "boysenberry", "elderberry", "currant",
    ],
    "vegetable": [
        "carrot", "potato", "sweet potato", "yam", "turnip", "parsnip", "radish", "beet",
        "onion", "garlic", "shallot", "leek", "chive", "broccoli", "cauliflower",
        "cabbage", "kale", "spinach", "chard", "arugula", "lettuce", "celery",
        "cucumber", "zucchini", "pumpkin", "squash", "eggplant", "pepper", "chili",
        "tomato", "avocado", "corn", "asparagus", "artichoke", "fennel", "brussels sprout",
        "pea", "bean", "lentil", "chickpea", "soybean", "tofu", "mushroom", "truffle",
        "ginger", "turmeric", "horseradish", "watercress", "bok choy", "okra",
    ],
    "drink": [
        "water", "sparkling water", "juice", "lemonade", "iced tea", "smoothie",
        "coffee", "espresso", "latte", "cappuccino", "americano", "cold brew",
        "tea", "green tea", "black tea", "herbal tea", "chai", "matcha",
        "milk", "oat milk", "almond milk", "hot chocolate",
        "wine", "red wine", "white wine", "rosé", "champagne", "prosecco",
        "beer", "ale", "lager", "stout", "porter", "cider",
        "whiskey", "vodka", "rum", "gin", "tequila", "brandy", "bourbon",
        "cocktail", "mojito", "margarita", "sangria", "mimosa",
    ],
    "nature and landscape": [
        "mountain", "peak", "summit", "ridge", "plateau", "mesa", "hill", "valley",
        "canyon", "gorge", "ravine", "cliff", "cave", "cavern", "volcano", "crater",
        "glacier", "iceberg", "tundra", "plain", "prairie", "steppe", "savanna",
        "desert", "dune", "oasis", "jungle", "rainforest", "forest", "woodland",
        "meadow", "marsh", "swamp", "bog", "wetland", "mangrove",
        "river", "stream", "creek", "brook", "waterfall", "rapids", "delta",
        "lake", "pond", "lagoon", "reservoir", "spring", "geyser",
        "ocean", "sea", "bay", "gulf", "strait", "fjord", "inlet", "cove", "beach",
        "island", "peninsula", "cape", "reef", "atoll", "archipelago",
    ],
    "weather and sky": [
        "sun", "sunshine", "sunset", "sunrise", "dawn", "dusk", "twilight",
        "moon", "moonlight", "eclipse", "star", "constellation", "nebula", "aurora",
        "cloud", "cumulus", "cirrus", "stratus", "fog", "mist", "haze", "smog",
        "rain", "drizzle", "shower", "downpour", "flood", "drought",
        "snow", "blizzard", "sleet", "hail", "frost", "ice",
        "wind", "breeze", "gale", "hurricane", "typhoon", "tornado", "cyclone",
        "thunder", "lightning", "storm", "rainbow", "heat wave", "cold snap",
    ],
    "plant and tree": [
        "oak", "elm", "maple", "birch", "beech", "ash", "willow", "poplar", "aspen",
        "pine", "spruce", "fir", "cedar", "redwood", "sequoia", "cypress", "juniper",
        "palm", "coconut", "bamboo", "cactus", "succulent", "aloe",
        "rose", "tulip", "daisy", "sunflower", "lily", "orchid", "lavender",
        "jasmine", "hibiscus", "magnolia", "iris", "chrysanthemum", "marigold",
        "moss", "lichen", "fern", "ivy", "vine", "seaweed", "kelp",
        "wheat", "rice", "corn", "oat", "barley", "rye", "sugarcane", "cotton",
        "root", "stem", "branch", "leaf", "petal", "pollen", "seed", "bark", "thorn",
    ],
    "body and anatomy": [
        "head", "skull", "forehead", "temple", "scalp", "face", "cheek", "jaw", "chin",
        "eye", "eyelid", "eyelash", "eyebrow", "pupil", "iris", "retina",
        "ear", "eardrum", "nose", "nostril", "mouth", "lip", "tongue", "tooth",
        "neck", "throat", "larynx", "shoulder", "arm", "elbow", "wrist", "hand",
        "finger", "thumb", "knuckle", "palm", "chest", "breast", "rib", "spine",
        "back", "hip", "abdomen", "pelvis", "buttock", "thigh", "knee", "shin",
        "calf", "ankle", "foot", "toe", "heel", "sole",
        "heart", "lung", "liver", "kidney", "stomach", "intestine", "pancreas",
        "brain", "spinal cord", "nerve", "artery", "vein", "capillary",
        "bone", "cartilage", "muscle", "tendon", "ligament", "skin", "hair", "nail",
    ],
    "health and medicine": [
        "doctor", "physician", "surgeon", "nurse", "paramedic", "pharmacist",
        "hospital", "clinic", "emergency room", "operating room", "pharmacy",
        "diagnosis", "symptom", "disease", "disorder", "syndrome", "condition",
        "infection", "virus", "bacteria", "fungus", "parasite",
        "fever", "cold", "flu", "pneumonia", "asthma", "diabetes", "cancer",
        "allergy", "inflammation", "arthritis", "hypertension", "anemia",
        "vaccine", "antibiotics", "medicine", "pill", "tablet", "capsule", "injection",
        "surgery", "transplant", "therapy", "physiotherapy", "rehabilitation",
        "pain", "headache", "migraine", "fatigue", "nausea", "dizziness",
        "wound", "fracture", "burn", "bruise", "scar", "bandage", "stitch",
        "mental health", "depression", "anxiety", "insomnia", "meditation",
    ],
    "emotion and psychology": [
        "joy", "happiness", "elation", "euphoria", "bliss", "contentment",
        "sadness", "grief", "sorrow", "melancholy", "despair", "heartbreak",
        "anger", "rage", "fury", "irritation", "frustration", "resentment",
        "fear", "terror", "dread", "panic", "phobia", "anxiety", "worry",
        "surprise", "shock", "astonishment", "wonder", "awe",
        "disgust", "revulsion", "contempt", "disdain",
        "love", "affection", "tenderness", "passion", "desire", "longing",
        "hate", "loathing", "jealousy", "envy", "bitterness",
        "pride", "shame", "guilt", "embarrassment", "humiliation",
        "trust", "suspicion", "betrayal", "loyalty",
        "hope", "optimism", "pessimism", "courage", "confidence", "doubt",
        "loneliness", "nostalgia", "empathy", "compassion", "gratitude",
        "boredom", "curiosity", "excitement", "anticipation", "calm", "peace",
    ],
    "color and appearance": [
        "red", "crimson", "scarlet", "ruby", "maroon", "burgundy",
        "orange", "amber", "copper", "tangerine",
        "yellow", "gold", "lemon", "mustard", "khaki",
        "green", "lime", "olive", "emerald", "sage", "teal", "mint",
        "blue", "navy", "cobalt", "royal blue", "sky blue", "azure", "turquoise", "cyan",
        "purple", "violet", "lavender", "indigo", "lilac", "magenta", "pink",
        "brown", "tan", "beige", "caramel", "chocolate", "rust",
        "black", "charcoal", "gray", "silver", "white", "cream", "ivory",
        "transparent", "translucent", "opaque", "glossy", "matte", "metallic",
    ],
    "mathematics": [
        "number", "integer", "fraction", "decimal", "percentage", "ratio", "proportion",
        "addition", "subtraction", "multiplication", "division", "exponent", "root",
        "algebra", "equation", "variable", "coefficient", "polynomial", "function",
        "geometry", "triangle", "circle", "square", "rectangle", "polygon", "angle",
        "calculus", "derivative", "integral", "limit", "infinity", "series",
        "statistics", "probability", "distribution", "average", "median", "variance",
        "matrix", "vector", "dimension", "coordinate", "graph", "topology",
        "prime", "factorial", "logarithm", "sine", "cosine", "tangent",
        "theorem", "proof", "axiom", "conjecture", "algorithm", "symmetry",
    ],
    "physics": [
        "force", "gravity", "mass", "weight", "acceleration", "velocity", "speed",
        "momentum", "inertia", "friction", "tension", "pressure",
        "energy", "kinetic energy", "potential energy", "work", "power",
        "wave", "frequency", "wavelength", "amplitude", "resonance", "interference",
        "light", "reflection", "refraction", "diffraction", "polarization",
        "electricity", "current", "voltage", "resistance", "capacitor", "inductor",
        "magnetism", "magnet", "field", "flux", "electromagnet",
        "atom", "electron", "proton", "neutron", "nucleus", "quark", "photon",
        "radiation", "radioactivity", "fission", "fusion", "plasma",
        "thermodynamics", "entropy", "temperature", "heat", "conduction", "convection",
        "relativity", "spacetime", "quantum", "uncertainty", "spin",
    ],
    "chemistry": [
        "element", "compound", "molecule", "bond", "reaction", "catalyst", "enzyme",
        "acid", "base", "salt", "pH", "oxidation", "reduction", "combustion",
        "hydrogen", "oxygen", "carbon", "nitrogen", "sulfur", "phosphorus", "chlorine",
        "sodium", "potassium", "calcium", "iron", "copper", "zinc", "silver", "gold",
        "polymer", "plastic", "rubber", "glass", "ceramic", "alloy", "crystal",
        "solution", "solvent", "solute", "concentration", "precipitation",
        "organic chemistry", "inorganic chemistry", "biochemistry", "electrochemistry",
    ],
    "biology and genetics": [
        "cell", "nucleus", "membrane", "mitochondria", "ribosome", "chromosome",
        "DNA", "RNA", "gene", "genome", "allele", "mutation", "protein", "amino acid",
        "evolution", "natural selection", "adaptation", "species", "population",
        "ecosystem", "habitat", "biodiversity", "food chain", "predator", "prey",
        "photosynthesis", "respiration", "metabolism", "digestion", "reproduction",
        "embryo", "fetus", "stem cell", "tissue", "organ", "organism",
        "taxonomy", "kingdom", "phylum", "genus", "bacteria", "archaea", "fungi",
        "parasite", "symbiosis", "mutualism", "predation", "competition",
    ],
    "technology and computing": [
        "computer", "laptop", "desktop", "server", "mainframe", "supercomputer",
        "processor", "CPU", "GPU", "memory", "RAM", "storage", "hard drive", "SSD",
        "keyboard", "mouse", "screen", "monitor", "printer", "scanner", "webcam",
        "internet", "network", "router", "firewall", "bandwidth", "protocol",
        "software", "operating system", "application", "program", "code", "compiler",
        "algorithm", "data structure", "array", "list", "tree", "graph", "hash",
        "database", "SQL", "query", "index", "cache", "API", "library", "framework",
        "machine learning", "neural network", "training", "model", "inference",
        "encryption", "cybersecurity", "password", "authentication", "vulnerability",
        "cloud", "container", "virtual machine", "deployment", "microservice",
        "smartphone", "tablet", "wearable", "sensor", "IoT", "drone", "robot",
        "blockchain", "cryptocurrency", "token", "smart contract",
    ],
    "society and politics": [
        "government", "state", "nation", "country", "republic", "monarchy",
        "democracy", "dictatorship", "parliament", "congress", "senate", "cabinet",
        "election", "vote", "ballot", "campaign", "policy", "legislation", "law",
        "president", "prime minister", "minister", "mayor", "governor", "ambassador",
        "constitution", "rights", "freedom", "equality", "justice", "citizenship",
        "protest", "revolution", "civil war", "coup", "referendum",
        "diplomacy", "treaty", "alliance", "sanction", "embargo",
        "war", "peace", "conflict", "ceasefire", "occupation", "refugee",
        "immigration", "border", "sovereignty", "colonialism", "imperialism",
        "ideology", "liberalism", "conservatism", "socialism", "communism", "fascism",
    ],
    "economics and finance": [
        "economy", "market", "trade", "commerce", "industry", "sector",
        "supply", "demand", "price", "inflation", "deflation", "recession",
        "GDP", "growth", "unemployment", "productivity", "investment",
        "bank", "central bank", "interest rate", "credit", "debt", "loan",
        "stock", "share", "dividend", "bond", "hedge fund", "portfolio",
        "currency", "dollar", "euro", "exchange rate", "reserve",
        "tax", "tariff", "subsidy", "budget", "deficit", "surplus",
        "corporation", "startup", "profit", "revenue", "cost", "capital",
        "globalization", "outsourcing", "free trade", "monopoly", "cartel",
    ],
    "education and knowledge": [
        "school", "classroom", "teacher", "student", "lecture", "lesson",
        "university", "college", "degree", "diploma", "graduation",
        "textbook", "curriculum", "syllabus", "exam", "grade", "scholarship",
        "research", "experiment", "hypothesis", "theory", "evidence", "data",
        "library", "archive", "encyclopedia", "dictionary",
        "literacy", "numeracy", "critical thinking", "reasoning", "analysis",
        "philosophy", "logic", "ethics", "epistemology", "metaphysics",
        "history", "archaeology", "anthropology", "sociology", "psychology",
    ],
    "art and design": [
        "painting", "drawing", "sketch", "illustration", "watercolor", "oil paint",
        "sculpture", "carving", "pottery", "ceramics", "mosaic",
        "photography", "portrait", "landscape", "abstract", "still life",
        "architecture", "interior design", "fashion", "textile", "jewelry",
        "graphic design", "typography", "logo", "branding", "poster",
        "animation", "digital art", "pixel art", "collage", "installation",
        "museum", "gallery", "exhibition", "canvas", "palette", "brush",
        "symmetry", "proportion", "perspective", "contrast", "texture", "composition",
    ],
    "music": [
        "melody", "harmony", "rhythm", "beat", "tempo", "pitch", "tone",
        "chord", "scale", "note", "key", "octave", "interval",
        "guitar", "piano", "violin", "cello", "bass", "drum", "percussion",
        "trumpet", "trombone", "saxophone", "flute", "clarinet", "oboe",
        "singer", "vocalist", "choir", "band", "orchestra", "conductor",
        "song", "album", "concert", "festival", "recording", "studio",
        "classical", "jazz", "blues", "rock", "pop", "hip hop", "electronic",
        "opera", "symphony", "sonata", "concerto", "fugue",
    ],
    "literature and language": [
        "novel", "story", "tale", "fable", "myth", "legend", "epic",
        "poem", "verse", "sonnet", "haiku", "ballad", "ode", "elegy",
        "author", "writer", "narrator", "character", "protagonist", "antagonist",
        "plot", "theme", "setting", "dialogue", "monologue", "metaphor", "symbol",
        "grammar", "syntax", "vocabulary", "word", "phrase", "sentence", "paragraph",
        "alphabet", "letter", "syllable", "rhyme", "accent", "dialect",
        "translation", "interpretation", "meaning", "context", "subtext",
        "comedy", "tragedy", "satire", "irony", "sarcasm", "hyperbole",
    ],
    "sports and games": [
        "football", "soccer", "basketball", "baseball", "volleyball", "handball",
        "tennis", "badminton", "squash", "ping pong", "golf", "croquet",
        "swimming", "diving", "water polo", "surfing", "rowing", "sailing",
        "running", "sprint", "marathon", "hurdles", "relay", "triathlon",
        "cycling", "mountain biking", "skateboarding", "skiing", "snowboarding",
        "boxing", "wrestling", "judo", "karate", "taekwondo", "fencing",
        "hockey", "ice hockey", "rugby", "cricket", "lacrosse", "polo",
        "chess", "checkers", "poker", "bridge", "dominoes", "dice",
        "athlete", "team", "coach", "referee", "championship", "trophy", "medal",
        "score", "goal", "point", "foul", "penalty", "overtime",
    ],
    "transportation": [
        "car", "sedan", "SUV", "van", "truck", "lorry", "pickup",
        "motorcycle", "scooter", "bicycle", "tricycle", "skateboard",
        "bus", "tram", "trolley", "monorail", "subway", "metro",
        "train", "locomotive", "freight train", "high speed rail",
        "airplane", "jet", "propeller plane", "helicopter", "glider",
        "rocket", "space shuttle", "satellite",
        "boat", "sailboat", "yacht", "ferry", "cruise ship", "cargo ship",
        "submarine", "hovercraft", "canoe", "kayak",
        "road", "highway", "motorway", "bridge", "tunnel", "roundabout",
        "airport", "railway station", "port", "harbor", "garage",
        "fuel", "engine", "wheel", "tire", "brake", "steering",
    ],
    "home and architecture": [
        "house", "apartment", "studio", "cottage", "mansion", "villa", "bungalow",
        "kitchen", "bathroom", "bedroom", "living room", "dining room", "hallway",
        "garage", "basement", "attic", "balcony", "patio", "terrace", "garden",
        "door", "window", "wall", "floor", "ceiling", "roof", "chimney",
        "staircase", "elevator", "corridor", "lobby", "porch",
        "chair", "sofa", "couch", "armchair", "bench", "stool",
        "table", "desk", "counter", "shelf", "cabinet", "wardrobe", "drawer",
        "bed", "mattress", "pillow", "blanket", "curtain", "rug", "carpet",
        "lamp", "chandelier", "mirror", "picture frame", "clock",
        "tower", "skyscraper", "castle", "palace", "temple", "cathedral",
        "mosque", "church", "synagogue", "monastery", "ruins",
    ],
    "time and calendar": [
        "second", "minute", "hour", "day", "week", "fortnight", "month", "quarter", "year",
        "decade", "century", "millennium", "era", "epoch", "age",
        "morning", "afternoon", "evening", "night", "midnight", "noon",
        "dawn", "dusk", "sunrise", "sunset", "twilight",
        "yesterday", "today", "tomorrow", "past", "present", "future",
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
        "spring", "summer", "autumn", "winter", "solstice", "equinox",
        "holiday", "weekend", "anniversary", "birthday", "deadline",
        "schedule", "calendar", "clock", "timer", "countdown",
    ],
    "action and movement": [
        "run", "sprint", "jog", "walk", "march", "stride", "shuffle", "limp",
        "jump", "leap", "bounce", "hop", "skip", "dive", "fall", "stumble",
        "swim", "float", "sink", "paddle", "row", "sail",
        "fly", "glide", "soar", "hover", "land", "take off",
        "climb", "crawl", "slide", "roll", "spin", "twist", "turn", "rotate",
        "push", "pull", "lift", "carry", "throw", "catch", "kick", "hit", "punch",
        "sit", "stand", "kneel", "bow", "stretch", "bend", "lean",
        "eat", "drink", "chew", "swallow", "bite", "sip",
        "sleep", "wake", "rest", "breathe", "yawn", "sneeze", "cough",
        "speak", "talk", "whisper", "shout", "laugh", "cry", "sing", "hum",
        "read", "write", "draw", "paint", "type", "click", "tap",
        "think", "remember", "forget", "imagine", "dream", "decide",
        "give", "take", "buy", "sell", "trade", "share", "steal",
        "build", "create", "make", "destroy", "break", "fix", "repair",
        "open", "close", "lock", "unlock", "start", "stop", "pause", "finish",
        "grow", "shrink", "expand", "contract", "change", "move", "stay",
        "learn", "teach", "study", "practice", "train", "compete", "win", "lose",
        "help", "protect", "attack", "escape", "hide", "search", "find",
    ],
    "quality and property": [
        "big", "large", "huge", "enormous", "gigantic", "tiny", "small", "little", "microscopic",
        "long", "tall", "high", "short", "low", "wide", "narrow", "deep", "shallow",
        "thick", "thin", "flat", "round", "sharp", "blunt", "rough", "smooth",
        "heavy", "light", "dense", "sparse", "solid", "hollow", "flexible", "rigid",
        "fast", "quick", "rapid", "slow", "gradual", "sudden", "constant", "variable",
        "strong", "powerful", "weak", "fragile", "durable", "tough", "soft", "hard",
        "hot", "warm", "cool", "cold", "icy", "freezing", "boiling",
        "wet", "damp", "moist", "dry", "arid",
        "clean", "pure", "dirty", "filthy", "sterile", "contaminated",
        "new", "fresh", "modern", "old", "ancient", "stale", "rotten",
        "bright", "luminous", "dark", "dim", "opaque", "clear",
        "loud", "noisy", "quiet", "silent",
        "rich", "wealthy", "poor", "cheap", "expensive", "free",
        "full", "packed", "empty", "sparse", "crowded", "lonely",
        "safe", "secure", "dangerous", "risky", "harmful", "harmless",
        "easy", "simple", "hard", "difficult", "complex", "complicated",
        "correct", "accurate", "wrong", "false", "true", "real", "fake",
        "beautiful", "attractive", "ugly", "plain",
        "funny", "humorous", "serious", "boring", "interesting", "exciting",
        "kind", "generous", "cruel", "selfish", "honest", "deceptive",
    ],
    "abstract concept": [
        "truth", "lie", "fact", "fiction", "reality", "illusion", "perception",
        "knowledge", "wisdom", "ignorance", "intelligence", "creativity",
        "power", "control", "authority", "influence", "freedom", "constraint",
        "order", "chaos", "balance", "harmony", "conflict",
        "time", "space", "infinity", "void", "existence", "nothingness",
        "identity", "self", "consciousness", "awareness", "memory", "imagination",
        "purpose", "meaning", "value", "belief", "faith", "doubt",
        "justice", "fairness", "morality", "ethics", "duty", "responsibility",
        "progress", "change", "continuity", "tradition", "innovation",
        "beauty", "art", "taste", "culture", "civilization",
        "life", "death", "birth", "growth", "decay", "rebirth",
        "unity", "diversity", "individuality", "community", "cooperation",
        "competition", "scarcity", "abundance", "need", "desire", "satisfaction",
        "risk", "opportunity", "failure", "success", "luck", "fate", "choice",
        "language", "symbol", "sign", "representation", "narrative", "myth",
    ],
}
